### ISSUE TITLE
.h é vida

### ISSUE THREAD

**Issue by rafaelcorsi** [brunoartc/Embarcados#1]
https://github.com/brunoartc/Embarcados/blob/55dabbd6520ab077c0d97360105289d638a6c08e/APS%20PIO-IO/src/main.c#L62

Tudo isso poderia ter ido para um .h e você daria `#include` depois! no main.c. O código ficaria muito mais 'limpo'

**Comment by brunoartc** [comment]
created .h file. 8cb73508f19df17ebccf6fd689e9732aa2101bee
