### ISSUE TITLE
função init

### ISSUE THREAD

**Issue by rafaelcorsi** [brunoartc/Embarcados#3]
https://github.com/brunoartc/Embarcados/blob/55dabbd6520ab077c0d97360105289d638a6c08e/APS%20PIO-IO/src/main.c#L532

tudo isso poderia ter ido para dentro de uma função `init()`. Código limpo = maior chance de sucesso!

**Comment by brunoartc** [comment]
added. 8cb73508f19df17ebccf6fd689e9732aa2101bee
