### ISSUE TITLE
magic number

### ISSUE THREAD

**Issue by rafaelcorsi** [brunoartc/Embarcados#4]
https://github.com/brunoartc/Embarcados/blob/55dabbd6520ab077c0d97360105289d638a6c08e/APS%20PIO-IO/src/main.c#L624

[Magic numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)) devem preferencialmente serem atribuidos a um #define/ const e bem comentados.

**Comment by brunoartc** [comment]
changed. 8cb73508f19df17ebccf6fd689e9732aa2101bee
