### ISSUE TITLE
comentários ajudam!

### ISSUE THREAD

**Issue by rafaelcorsi** [brunoartc/Embarcados#5]
https://github.com/brunoartc/Embarcados/blob/55dabbd6520ab077c0d97360105289d638a6c08e/APS%20PIO-IO/src/main.c#L414

Um pouco de comentário no código é bom, poderia explicar um pouco cada função...

**Comment by brunoartc** [comment]
added. 8cb73508f19df17ebccf6fd689e9732aa2101bee
