### ISSUE TITLE
repeteco = função / 

### ISSUE THREAD

**Issue by rafaelcorsi** [brunoartc/Embarcados#6]
https://github.com/brunoartc/Embarcados/blob/55dabbd6520ab077c0d97360105289d638a6c08e/APS%20PIO-IO/src/main.c#L608

Trechos de códigos similares devem virar funções para:

   1. reaproveitamento de código
   1. deixar o código mais fácil de entender!

**Comment by brunoartc** [comment]
done. 8cb73508f19df17ebccf6fd689e9732aa2101bee
