### ISSUE TITLE
video

### ISSUE THREAD

**Issue by rafaelcorsi** [brunoartc/Embarcados#7]
uma pena que filmou no escuro, a qualidade ficou bem ruim. O projeto está muito legal!

 consegue fazer outro vídeo com uma qualidade melhor para eu usar como exemplo? 

abs

**Comment by brunoartc** [comment]
arquivo original -> https://myc.toranja.xyz/index.php/s/D9kxQCtS4ibitfT
link do youtube -> https://youtu.be/kOhiKLVERl8

**Comment by rafaelcorsi** [comment]
Nos corrigimos esse bug no Oled, só atualizar o Examples!

**Comment by brunoartc** [comment]
solved. #9
